version: '3'

networks:
  spring-state-machine-demo-network:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    networks:
      - spring-state-machine-demo-network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring-state-machine-demo-db